PR27739: modernize java/byteman probing support
Use modern byteman's ability to load helper .jar on demand, and let
that .jar load the JNI .so on demand, all from full
$pkglibexecdir-based pathnames.  That way, the rpm .spec does not need
to worry about symlinking, and stapbm doesn't have to deal with
anything except the convenient bminstall/bmsubmit frontend scripts.

diff --git a/java/stapbm.in b/java/stapbm.in
--- a/java/stapbm.in
+++ b/java/stapbm.in
@@ -53,73 +53,21 @@ SYSTEMTAP_VERBOSE=${SYSTEMTAP_VERBOSE-0}
 
 if [ "$SYSTEMTAP_VERBOSE" != "0" ]; then
     BYTEMAN_INSTALL_OPTS="$BYTEMAN_INSTALL_OPTS -Dorg.jboss.byteman.verbose"
+    set -x
 else
     exec >/dev/null
     # NB: preserve stderr
 fi
 
-# the byteman and byteman-submit jars should be in ${BYTEMAN_HOME}/lib
-BYTEMAN_JAR=${BYTEMAN_HOME}/byteman.jar
-if [ ! -r ${BYTEMAN_JAR} ]; then
-    exec 1>&2
-    echo "Missing $BYTEMAN_JAR"
-    exit 1
-fi
-
-BYTEMAN_SUBMIT_JAR=${BYTEMAN_HOME}/byteman-submit.jar
-if [ ! -r ${BYTEMAN_SUBMIT_JAR} ]; then
-    exec 1>&2
-    echo "Missing $BYTEMAN_SUBMIT_JAR"
-    exit 1
-fi
-
-BYTEMAN_INSTALL_JAR=${BYTEMAN_HOME}/byteman-install.jar
-if [ ! -r ${BYTEMAN_INSTALL_JAR} ]; then
-    exec 1>&2
-    echo "Missing $BYTEMAN_INSTALL_JAR"
-    exit 1
-fi
-
-
-TOOLS_JAR=${JAVA_HOME}/lib/tools.jar
-if [ ! -f ${TOOLS_JAR} ]; then
-    exec 1>&2
-    echo "Missing $TOOLS_JAR"
-    exit 1
-fi
-
-# resolve $*prefix fully
 prefix=@prefix@
 exec_prefix=@exec_prefix@
-pkglibexecdir=@libexecdir@/@PACKAGE@
-pkglibexecdir=`eval echo $pkglibexecdir`
-pkglibexecdir=`eval echo $pkglibexecdir`
+pkglibexecdir=@pkglibexecdir@
 
 HELPERSDT_JAR=${pkglibexecdir}/HelperSDT.jar
 if [ ! -f ${HELPERSDT_JAR} ]; then
     exec 1>&2
     echo "Missing $HELPERSDT_JAR"
     exit 1
-fi
-
-
-# The JVM that invokes byteman will get classpath/etc. settings from
-# this shell script to look directly under our $prefix.  However, for
-# the target JVM, the HelperSDT* stuff needs to be installed under
-# that JVM's paths.
-
-num=`ls -1 ${JAVA_HOME}/jre/lib/ext/HelperSDT.jar ${JAVA_HOME}/jre/lib/*/libHelperSDT_*.so 2>/dev/null | wc -l`
-if [ $num -lt 2 ]; then
-    exec 1>&2
-    echo "Missing HelperSDT JNI class/shared library"
-    echo "Install them like this, as root:"
-    echo ""
-    echo "for so in ${pkglibexecdir}/libHelperSDT_*.so; do"
-    echo '  arch=`basename $so | cut -f2 -d_ | cut -f1 -d.`'
-    echo "  ln -sf ${pkglibexecdir}/libHelperSDT_"'${arch}'".so ${JAVA_HOME}/jre/lib/"'${arch}'"/"
-    echo "done"
-    echo "ln -sf ${pkglibexecdir}/HelperSDT.jar ${JAVA_HOME}/jre/lib/ext/"
-#   exit 1
 fi
 
 flagdir="$SYSTEMTAP_DIR/java"
@@ -134,8 +82,8 @@ mkdir -p $flagdir
 if ! [[ $arg_jvmpid =~ ^[0-9]+$ ]]; then
     target_pid=`jps -l | grep $arg_jvmpid | cut -f1 -d" "`
     for target in $target_pid; do
-	$0 $arg_command $target $arg_rulename $arg_class "$arg_method" $arg_argcount $arg_probetype $arg_backtrace
-    done;
+	$0 "$arg_command" "$target" "$arg_rulename" "$arg_class" "$arg_method" "$arg_argcount" "$arg_probetype" "$arg_backtrace"
+    done
     exit 0
 else
     target_pid=$arg_jvmpid
@@ -158,7 +106,6 @@ if [ -s $byteman_installed_portfile ]; then
         echo "Byteman agent reused for java pid $target_pid, port $bmport"
     fi
 
-
     # XXX: liveness-check the port; bmsubmit with no argument just lists current rules
     # if fails, delete the _portfile and retry everything
 else
@@ -175,16 +122,19 @@ else
 # byteman and its use of VMAttach libraries, for our case it always makes sense to use
 # byteman classes directly and avoid -javaagent
 
-    if [ "$SYSTEMTAP_VERBOSE" != "0" ]; then
-	echo java -classpath ${BYTEMAN_INSTALL_JAR}:${BYTEMAN_JAR}:${TOOLS_JAR}:${HELPERSDT_JAR} org.jboss.byteman.agent.install.Install -b -p $bmport $BYTEMAN_INSTALL_OPTS $target_pid
-    fi
-    java -classpath ${BYTEMAN_INSTALL_JAR}:${BYTEMAN_JAR}:${TOOLS_JAR}:${HELPERSDT_JAR} org.jboss.byteman.agent.install.Install -b -p $bmport $BYTEMAN_INSTALL_OPTS $target_pid
+    bminstall -b -p $bmport $BYTEMAN_INSTALL_OPTS $target_pid
     if [ $? -ne 0 ]; then
         echo "Byteman agent failed to install for java pid $target_pid, port $bmport"
         exit 1
     fi
-    echo $bmport > $byteman_installed_portfile
+    bmsubmit -p $bmport -s $HELPERSDT_JAR
+    if [ $? -ne 0 ]; then
+        echo "Byteman agent failed to load HelperSDT.jar java pid $target_pid, port $bmport"
+        exit 1
+    fi
 
+    echo $bmport > $byteman_installed_portfile
+    
     if [ "$SYSTEMTAP_VERBOSE" != "0" ]; then
         echo "Byteman agent installed for java pid $target_pid, port $bmport"
     fi
@@ -260,8 +210,4 @@ else
     bmcmd=-l
 fi
 
-if [ "$SYSTEMTAP_VERBOSE" != "0" ]; then
-    echo java -classpath ${BYTEMAN_SUBMIT_JAR}:${BYTEMAN_JAR}:${HELPERSDT_JAR} org.jboss.byteman.agent.submit.Submit -p $bmport $bmcmd $btmfile
-fi
-
-exec java -classpath ${BYTEMAN_SUBMIT_JAR}:${BYTEMAN_JAR}:${HELPERSDT_JAR} org.jboss.byteman.agent.submit.Submit -p $bmport $bmcmd $btmfile
+bmsubmit -p $bmport $bmcmd $btmfile
